# Tamarack Clearing — light
# 🌾 https://github.com/buckleypaul/tamarack-theme

palette = 0=#554c3e
palette = 1=#a8422f
palette = 2=#4e7c3a
palette = 3=#8f6a14
palette = 4=#4a6e8c
palette = 5=#9d4382
palette = 6=#2a7b87
palette = 7=#a0947f
palette = 8=#6e6454
palette = 9=#bc5340
palette = 10=#5c8e45
palette = 11=#a07920
palette = 12=#587fa0
palette = 13=#b25395
palette = 14=#358995
palette = 15=#877c69

background = #faf7f1
foreground = #2e271e
cursor-color = #a35514
cursor-text = #faf7f1
selection-background = #bcd2d1
selection-foreground = #2e271e
split-divider-color = #cfc4ae
unfocused-split-fill = #ebe5d9
