# Tamarack Fall — dark
# 🍂 https://github.com/buckleypaul/tamarack-theme

palette = 0=#332c25
palette = 1=#de6d59
palette = 2=#90bb7d
palette = 3=#e2ab2d
palette = 4=#89a5bc
palette = 5=#b389a7
palette = 6=#73aeb7
palette = 7=#c5beb7
palette = 8=#403730
palette = 9=#e38575
palette = 10=#a3c693
palette = 11=#e6b74a
palette = 12=#9eb5c8
palette = 13=#c09db6
palette = 14=#89bbc2
palette = 15=#e6e0db

background = #1b1612
foreground = #e6e0db
cursor-color = #f48d38
cursor-text = #1b1612
selection-background = #354444
selection-foreground = #e6e0db
split-divider-color = #403730
unfocused-split-fill = #0f0c0a
