# Tamarack Thicket — dark
# 🌲 https://github.com/buckleypaul/tamarack-theme

palette = 0=#26322b
palette = 1=#d67464
palette = 2=#8fbe71
palette = 3=#dcae57
palette = 4=#88a6c2
palette = 5=#b988aa
palette = 6=#66b2ba
palette = 7=#b8c4bb
palette = 8=#313f37
palette = 9=#e08a7b
palette = 10=#a0cb84
palette = 11=#e6bc6f
palette = 12=#9cb6ce
palette = 13=#cb9fbe
palette = 14=#7bc1c8
palette = 15=#dfe5dc

background = #131a16
foreground = #dfe5dc
cursor-color = #e9954d
cursor-text = #131a16
selection-background = #2c4847
selection-foreground = #dfe5dc
split-divider-color = #313f37
unfocused-split-fill = #0a0f0c
