# Tamarack Spring — light
# 🌱 https://github.com/buckleypaul/tamarack-theme

palette = 0=#485241
palette = 1=#a14839
palette = 2=#4a7d33
palette = 3=#8c6b1f
palette = 4=#4f6e87
palette = 5=#964a7f
palette = 6=#337b86
palette = 7=#8e9b84
palette = 8=#5f6a58
palette = 9=#ba5342
palette = 10=#58953d
palette = 11=#a78025
palette = 12=#5b7f9c
palette = 13=#ab5692
palette = 14=#3c919e
palette = 15=#76836d

background = #f5f9f2
foreground = #252c20
cursor-color = #4a7d33
cursor-text = #f5f9f2
selection-background = #bbd3d2
selection-foreground = #252c20
split-divider-color = #bdcab3
unfocused-split-fill = #e1e8dc
