# Tamarack Winter — dark
# 🌲 https://github.com/buckleypaul/tamarack-theme

palette = 0=#26322b
palette = 1=#cd796a
palette = 2=#81c165
palette = 3=#d3b163
palette = 4=#8ba6bd
palette = 5=#b48aa8
palette = 6=#5eb2bf
palette = 7=#b8c4bb
palette = 8=#313f37
palette = 9=#d58f83
palette = 10=#94cb7d
palette = 11=#dabe7d
palette = 12=#a0b6c9
palette = 13=#c19eb7
palette = 14=#76bdc8
palette = 15=#dfe5dc

background = #131a16
foreground = #dfe5dc
cursor-color = #44bb9d
cursor-text = #131a16
selection-background = #2a4849
selection-foreground = #dfe5dc
split-divider-color = #313f37
unfocused-split-fill = #0a0f0c
