# Tamarack Summer — light
# 🌻 https://github.com/buckleypaul/tamarack-theme

palette = 0=#554c3e
palette = 1=#a04839
palette = 2=#527b41
palette = 3=#91690a
palette = 4=#4f6e87
palette = 5=#95497f
palette = 6=#337a84
palette = 7=#a0947f
palette = 8=#6e6454
palette = 9=#b85342
palette = 10=#60914c
palette = 11=#b07f0c
palette = 12=#5b7f9c
palette = 13=#ab5492
palette = 14=#3c909c
palette = 15=#877c69

background = #faf7f1
foreground = #2e271e
cursor-color = #a95109
cursor-text = #faf7f1
selection-background = #bed1d0
selection-foreground = #2e271e
split-divider-color = #cfc4ae
unfocused-split-fill = #ebe5d9
